# Generated by Django 4.2.5 on 2023-09-19 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='hashtag',
            new_name='category',
        ),
    ]
